// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: stremio/core/runtime/field.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Stremio_Core_Runtime_Field: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case ctx // = 0
  case authLink // = 1
  case continueWatchingPreview // = 2
  case discover // = 3
  case library // = 4
  case libraryByType // = 5
  case board // = 6
  case search // = 7
  case metaDetails // = 8
  case addons // = 9
  case addonDetails // = 10
  case streamingServer // = 11
  case player // = 12

  public init() {
    self = .ctx
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .ctx
    case 1: self = .authLink
    case 2: self = .continueWatchingPreview
    case 3: self = .discover
    case 4: self = .library
    case 5: self = .libraryByType
    case 6: self = .board
    case 7: self = .search
    case 8: self = .metaDetails
    case 9: self = .addons
    case 10: self = .addonDetails
    case 11: self = .streamingServer
    case 12: self = .player
    default: return nil
    }
  }

  public var rawValue: Int {
    switch self {
    case .ctx: return 0
    case .authLink: return 1
    case .continueWatchingPreview: return 2
    case .discover: return 3
    case .library: return 4
    case .libraryByType: return 5
    case .board: return 6
    case .search: return 7
    case .metaDetails: return 8
    case .addons: return 9
    case .addonDetails: return 10
    case .streamingServer: return 11
    case .player: return 12
    }
  }

}

#if swift(>=4.2)

extension Stremio_Core_Runtime_Field: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension Stremio_Core_Runtime_Field: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Stremio_Core_Runtime_Field: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Ctx"),
    1: .same(proto: "AuthLink"),
    2: .same(proto: "ContinueWatchingPreview"),
    3: .same(proto: "Discover"),
    4: .same(proto: "Library"),
    5: .same(proto: "LibraryByType"),
    6: .same(proto: "Board"),
    7: .same(proto: "Search"),
    8: .same(proto: "MetaDetails"),
    9: .same(proto: "Addons"),
    10: .same(proto: "AddonDetails"),
    11: .same(proto: "StreamingServer"),
    12: .same(proto: "Player"),
  ]
}
